In [1]:
import torch
from pyplus.pytorch.simple import TorchPlus
from torchvision.datasets.mnist import MNIST

In [2]:
mnist=MNIST(root='./data/',download=True,)

In [3]:
train=mnist.train_data.reshape(-1,28*28)
label=mnist.train_labels

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torchvision/datasets/mnist.py:75: UserWarning: train_data has been renamed data
  warnings.warn("train_data has been renamed data")
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torchvision/datasets/mnist.py:65: UserWarning: train_labels has been renamed targets
  warnings.warn("train_labels has been renamed targets")


In [4]:
label.shape

torch.Size([60000])

In [5]:
tp = TorchPlus()
tp.meta_data_per_iteration=100
tp.meta_epoch=10
tp.meta_optimizer=torch.optim.Adam
tp.meta_activator=torch.relu
def process(activator):
    proc = tp.input('x',train.float()) @ tp.parameter('param',torch.rand(28*28,512).float())
    proc = activator(proc)
    proc = proc @ tp.parameter('param2',torch.rand(512,512).float())
    proc = activator(proc)
    proc = proc @ tp.parameter('param3',torch.rand(512,1).float())
    
    tp.label('label',label.float())
    return proc
tp.process=process

In [6]:
type(train)

torch.Tensor

In [7]:
model=tp.train(show_sequence_process=True)

current data : 0 to 100
current data : 100 to 200
current data : 200 to 300
current data : 300 to 400
current data : 400 to 500
current data : 500 to 600
current data : 600 to 700
current data : 700 to 800
current data : 800 to 900


/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/nn/modules/loss.py:535: UserWarning: Using a target size (torch.Size([100, 1])) that is different to the input size (torch.Size([1, 100])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)


current data : 900 to 1000
current data : 1000 to 1100
current data : 1100 to 1200
current data : 1200 to 1300
current data : 1300 to 1400
current data : 1400 to 1500
current data : 1500 to 1600
current data : 1600 to 1700
current data : 1700 to 1800
current data : 1800 to 1900
current data : 1900 to 2000
current data : 2000 to 2100
current data : 2100 to 2200
current data : 2200 to 2300
current data : 2300 to 2400
current data : 2400 to 2500
current data : 2500 to 2600
current data : 2600 to 2700
current data : 2700 to 2800
current data : 2800 to 2900
current data : 2900 to 3000
current data : 3000 to 3100
current data : 3100 to 3200
current data : 3200 to 3300
current data : 3300 to 3400
current data : 3400 to 3500
current data : 3500 to 3600
current data : 3600 to 3700
current data : 3700 to 3800
current data : 3800 to 3900
current data : 3900 to 4000
current data : 4000 to 4100
current data : 4100 to 4200
current data : 4200 to 4300
current data : 4300 to 4400
current data : 4400 t

In [8]:
test_data=mnist.test_data
test_label=mnist.test_labels

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torchvision/datasets/mnist.py:80: UserWarning: test_data has been renamed data
  warnings.warn("test_data has been renamed data")
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torchvision/datasets/mnist.py:70: UserWarning: test_labels has been renamed targets
  warnings.warn("test_labels has been renamed targets")


In [9]:
tp.all_predict_tensors.get_tensor(name='x').tensor.shape

torch.Size([60000, 784])

In [10]:
test_one = test_data.reshape(-1,28*28)[0:10].float()

In [11]:
test_one.shape

torch.Size([10, 784])

In [12]:
model(x=test_one)

[tensor([[33522.5000]], grad_fn=<MmBackward0>),
 tensor([[59481.]], grad_fn=<MmBackward0>),
 tensor([[212.]], grad_fn=<MmBackward0>),
 tensor([[58830.]], grad_fn=<MmBackward0>),
 tensor([[28811.]], grad_fn=<MmBackward0>),
 tensor([[8145.5000]], grad_fn=<MmBackward0>),
 tensor([[30303.]], grad_fn=<MmBackward0>),
 tensor([[54752.]], grad_fn=<MmBackward0>),
 tensor([[9292.5000]], grad_fn=<MmBackward0>),
 tensor([[-2229.]], grad_fn=<MmBackward0>)]

In [13]:
tp.all_predict_tensors.get_tensor(name='param').tensor

tensor([[0.1359, 0.1616, 0.3561,  ..., 0.5091, 0.3434, 0.9544],
        [0.3766, 0.3028, 0.8424,  ..., 0.8463, 0.3527, 0.1291],
        [0.5713, 0.7761, 0.6880,  ..., 0.3482, 0.2328, 0.0360],
        ...,
        [0.8427, 0.1562, 0.6199,  ..., 0.3094, 0.6122, 0.5968],
        [0.5812, 0.3744, 0.0814,  ..., 0.7100, 0.9191, 0.5658],
        [0.5873, 0.7923, 0.9444,  ..., 0.0404, 0.8176, 0.2927]],
       requires_grad=True)